/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
      extend: {
          colors: {
              "surface-variant": "#e3e3de",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed": "#1c1b1b",
              "primary-container": "#0055ff",
              "inverse-primary": "#b6c4ff",
              "surface-container-highest": "#e3e3de",
              "tertiary": "#504f4f",
              "background": "#fafaf5",
              "on-surface-variant": "#434656",
              "on-tertiary": "#ffffff",
              "on-surface": "#1a1c19",
              "tertiary-container": "#686767",
              "surface-container": "#eeeee9",
              "on-secondary-fixed": "#1c1b1b",
              "primary": "#0041c8",
              "on-primary-container": "#e3e6ff",
              "secondary": "#5f5e5e",
              "error-container": "#ffdad6",
              "inverse-surface": "#2f312e",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#001551",
              "on-error-container": "#93000a",
              "tertiary-fixed-dim": "#c8c6c5",
              "on-secondary-container": "#656464",
              "secondary-fixed-dim": "#c8c6c5",
              "surface-tint": "#004dea",
              "on-secondary": "#ffffff",
              "on-tertiary-container": "#eae6e6",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "surface-dim": "#dadad5",
              "surface-container-high": "#e8e8e3",
              "on-primary-fixed-variant": "#0039b3",
              "secondary-container": "#e5e2e1",
              "primary-fixed-dim": "#b6c4ff",
              "on-tertiary-fixed-variant": "#474646",
              "on-secondary-fixed-variant": "#474646",
              "tertiary-fixed": "#e5e2e1",
              "surface": "#fafaf5",
              "primary-fixed": "#dce1ff",
              "surface-container-low": "#f4f4ef",
              "secondary-fixed": "#e5e2e1",
              "outline-variant": "#c3c5d9",
              "outline": "#737688",
              "surface-bright": "#fafaf5",
              "inverse-on-surface": "#f1f1ec",
              "on-background": "#1a1c19"
          },
          fontFamily: {
              "headline": ["Newsreader", "serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Space Grotesk", "monospace"]
          },
          borderRadius: {
              "DEFAULT": "0px",
              "lg": "0px",
              "xl": "0px",
              "full": "9999px"
          },
      },
  },
  plugins: [],
}
