// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {shared} from '../models';

export function AddExtraDirectory(arg1:string):Promise<void>;

export function BrowseForDirectory():Promise<string>;

export function CheckSystemGPU():Promise<boolean>;

export function GetAPIConfig():Promise<main.APIConfig>;

export function GetEngineStatus():Promise<string>;

export function GetFolderChildren(arg1:string):Promise<Array<main.FolderState>>;

export function GetGPUAcceleration():Promise<boolean>;

export function GetHomeFolders():Promise<Array<main.FolderState>>;

export function GetIndexingStatus():Promise<main.IndexingStatus>;

export function GetOptimizerStatus():Promise<shared.OptimizerStatus>;

export function OpenFileNative(arg1:string):Promise<void>;

export function RegenerateAPIKey():Promise<string>;

export function RemoveExtraDirectory(arg1:string):Promise<void>;

export function RetryEngineInit():Promise<void>;

export function Search(arg1:string):Promise<Array<shared.SearchResult>>;

export function SetAPIEnabled(arg1:boolean):Promise<void>;

export function SetAPIPort(arg1:number):Promise<void>;

export function SetDirPathOnly(arg1:string,arg2:boolean):Promise<void>;

export function SetFolderIndexed(arg1:string,arg2:boolean):Promise<void>;

export function SetGPUAcceleration(arg1:boolean):Promise<void>;

export function SetMCPEnabled(arg1:boolean):Promise<void>;

export function SetMCPKey(arg1:string):Promise<void>;

export function SubmitFeedback(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function TestLLMEndpoint(arg1:string,arg2:string):Promise<string>;
