// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExtraDirectory(arg1) {
  return window['go']['main']['App']['AddExtraDirectory'](arg1);
}

export function BrowseForDirectory() {
  return window['go']['main']['App']['BrowseForDirectory']();
}

export function CheckSystemGPU() {
  return window['go']['main']['App']['CheckSystemGPU']();
}

export function GetAPIConfig() {
  return window['go']['main']['App']['GetAPIConfig']();
}

export function GetEngineStatus() {
  return window['go']['main']['App']['GetEngineStatus']();
}

export function GetFolderChildren(arg1) {
  return window['go']['main']['App']['GetFolderChildren'](arg1);
}

export function GetGPUAcceleration() {
  return window['go']['main']['App']['GetGPUAcceleration']();
}

export function GetHomeFolders() {
  return window['go']['main']['App']['GetHomeFolders']();
}

export function GetIndexingStatus() {
  return window['go']['main']['App']['GetIndexingStatus']();
}

export function GetOptimizerStatus() {
  return window['go']['main']['App']['GetOptimizerStatus']();
}

export function OpenFileNative(arg1) {
  return window['go']['main']['App']['OpenFileNative'](arg1);
}

export function RegenerateAPIKey() {
  return window['go']['main']['App']['RegenerateAPIKey']();
}

export function RemoveExtraDirectory(arg1) {
  return window['go']['main']['App']['RemoveExtraDirectory'](arg1);
}

export function RetryEngineInit() {
  return window['go']['main']['App']['RetryEngineInit']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetAPIEnabled(arg1) {
  return window['go']['main']['App']['SetAPIEnabled'](arg1);
}

export function SetAPIPort(arg1) {
  return window['go']['main']['App']['SetAPIPort'](arg1);
}

export function SetDirPathOnly(arg1, arg2) {
  return window['go']['main']['App']['SetDirPathOnly'](arg1, arg2);
}

export function SetFolderIndexed(arg1, arg2) {
  return window['go']['main']['App']['SetFolderIndexed'](arg1, arg2);
}

export function SetGPUAcceleration(arg1) {
  return window['go']['main']['App']['SetGPUAcceleration'](arg1);
}

export function SetMCPEnabled(arg1) {
  return window['go']['main']['App']['SetMCPEnabled'](arg1);
}

export function SetMCPKey(arg1) {
  return window['go']['main']['App']['SetMCPKey'](arg1);
}

export function SubmitFeedback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3, arg4, arg5);
}

export function TestLLMEndpoint(arg1, arg2) {
  return window['go']['main']['App']['TestLLMEndpoint'](arg1, arg2);
}
